# License: MIT
# Copyright © 2024 Frequenz Energy-as-a-Service GmbH

"""Generated protocol buffer code for demo.proto."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# This is a minimal representation of what protoc would generate
# In a real scenario, this would be generated by the protoc compiler

class HelloRequest(_message.Message):
    """Hello request message."""
    
    def __init__(self, name: str = "", count: int = 0) -> None:
        """Initialize HelloRequest."""
        super().__init__()
        self.name = name
        self.count = count


class HelloReply(_message.Message):
    """Hello reply message."""
    
    def __init__(self, message: str = "", sequence: int = 0) -> None:
        """Initialize HelloReply."""
        super().__init__()
        self.message = message
        self.sequence = sequence